language: node_js

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

before_script:
  - phantomjs --version
  - cd spec/support/test-pages && python -m SimpleHTTPServer 8888 &

script:
  - npm run build
  - npm run test
  - node lib/bin/whoopsie.js gallery spec/support/test-config.yaml --debug
