language: node_js

node_js:
  - "8"

before_script:
  - phantomjs --version
  - cd spec/support/test-pages && python -m SimpleHTTPServer 8888 &

script:
  - npm run test
  # - node bin/whoopsie.js gallery spec/support/test-config.yaml --debug

notifications:
  email: false
