sites:
  - http://www.bbc.co.uk/news

pages:
  - path: /
  - path: /technology
  - path: /technology-36387563

widths:
  - 320
  - 600

ignoreSelectors:

renderWaitTime: 3000

outDir: results/

failureThreshold: 10

fuzz: 5
