# Two URLs to run tests against. The first is considered to be the baseline
sites:
  - http://www.bbc.com
  - http://www.test.bbc.com

# List of pages to test on each site
pages:
  # Each page must have a path (relative to the site URLs).
  # By default, the whole page will be captured.
  - path: /news

  # Pages can also have a list of selectors. Rather than capturing the whole
  # page, an image of each selector will be captured.
  - path: /news
    selectors:
      - .nw-c-top-stories
      - .nw-c-must-see
      - .nw-c-full-story
      - .nw-c-most-read

  # Pages can be named to make test results easier to read
  - path: /news
    name: News Index

# Viewport configurations to run tests with
# Each viewport can have the following properties:
#  - width (required)
#  - height: (default: 1000)
#  - isMobile (default: false)
#  - javascriptDisabled (default: false)
#  - name
viewports:
  - width: 640
    isMobile: true

  - width: 320
    height: 480
    isMobile: true
    javascriptDisabled: true
    name: Core Experience

# Which browser to run the tests with. Available browsers:
#  - HeadlessChrome
browser: HeadlessChrome

# List of requests to block.
# Request URLs are partially matched against each value
blockRequests:
  - static.bbc.co.uk/bbcdotcom
  - bbc.co.uk/wwscripts

# List of CSS selectors to hide (display: none) before capturing a screenshot
ignoreSelectors:
  - '#blq-global'
  - '#orb-header'
  - '#orb-footer'
  - '.nw-c-breaking-news-banner'
  - '#breaking-news-container'

# Where to store Whoopsie output
outDir: whoopsie/

# Input file for the generate-gallery command
inFile: whoopsie/results.json

# How different two pages should be (as a percentage) for a test to fail
failureThreshold: 10

# How many milliseconds the network should be idle for before capturing the page
networkIdleTimeout: 3000

# How much fuzz should be applied when calculating differences
# See http://www.imagemagick.org/Usage/color_basics/#fuzz for a full explanation
fuzz: 5

# Whether to scroll to the end of the page before capturing a screenshot
scroll: true

# Whether to run the capture process in headless mode
headless: true
