# Two URLs to run tests against. The first is considered to be the baseline
sites:
  - https://www.bbc.co.uk/news
  - https://www.test.bbc.co.uk/news

# Screen widths to run tests at
widths:
  - 420
  - 680
  - 1040

# List of paths to test (relative to site URLs)
urls:
  - /
  - /technology
  - /technology-36387563

# How different two pages should be (as a percentage) for a test to fail
failure_threshold: 10

# How much fuzz should be applied when calculating differences
# See http://www.imagemagick.org/Usage/color_basics/#fuzz for a full explanation
fuzz: 5
