# Two URLs to run tests against. The first is considered to be the baseline
sites:
  - http://www.bbc.co.uk/news
  - http://www.test.bbc.co.uk/news

# Screen widths to run tests at
widths:
  - 320
  - 680
  - 1040

# List of paths to test (relative to site URLs)
urls:
  - /
  - /technology
  - /technology-36387563

# List of CSS selectors to hide (display: none) before capturing a screenshot
ignoreSelectors:
  - '#blq-global'
  - '#orb-header'
  - '#orb-footer'
  - '#breaking-news-container'

# How long (in milliseconds) to wait before capturing a screenshot
renderWaitTime: 3000

# Directory in which to save test results
galleryDir: results/

# How different two pages should be (as a percentage) for a test to fail
failureThreshold: 10

# How much fuzz should be applied when calculating differences
# See http://www.imagemagick.org/Usage/color_basics/#fuzz for a full explanation
fuzz: 5
